import React, { useEffect, useRef } from 'react';
import ReactMarkdown from 'react-markdown';
import { Prism as SyntaxHighlighter } from 'react-syntax-highlighter';
import { vscDarkPlus } from 'react-syntax-highlighter/dist/esm/styles/prism';
import { Message, Role } from '../types';
import { User, Globe, Search, Copy } from 'lucide-react';
import { NexusLogo } from './NexusLogo';
import { ImageGenProgress } from './ImageGenProgress';

interface MessageListProps {
  messages: Message[];
  isLoading: boolean;
}

export const MessageList: React.FC<MessageListProps> = ({ messages, isLoading }) => {
  const bottomRef = useRef<HTMLDivElement>(null);

  useEffect(() => {
    bottomRef.current?.scrollIntoView({ behavior: 'smooth' });
  }, [messages, isLoading]);

  return (
    <div className="flex-1 overflow-y-auto p-4 space-y-6 pb-32 custom-scrollbar">
      {messages.map((msg) => {
        if (msg.isGeneratingImage) {
            return (
                <div key={msg.id} className="flex justify-start gap-4 max-w-4xl mx-auto w-full">
                     <div className="w-8 h-8 rounded-full bg-gradient-to-br from-blue-500 to-purple-600 flex-shrink-0 flex items-center justify-center shadow-lg mt-1 border border-white/10">
                        <NexusLogo className="w-5 h-5" />
                    </div>
                    <div className="flex-1">
                        <ImageGenProgress />
                    </div>
                </div>
            );
        }
        
        return (
            <div 
            key={msg.id} 
            className={`flex gap-4 max-w-4xl mx-auto ${msg.role === Role.USER ? 'justify-end' : 'justify-start'}`}
            >
            {msg.role === Role.MODEL && (
                <div className="w-8 h-8 rounded-full bg-gradient-to-br from-blue-500 to-purple-600 flex-shrink-0 flex items-center justify-center shadow-lg mt-1 border border-white/10">
                    <NexusLogo className="w-5 h-5" />
                </div>
            )}

            <div className={`flex flex-col gap-1 max-w-[85%] ${msg.role === Role.USER ? 'items-end' : 'items-start'}`}>
                
                {/* Attachments */}
                {msg.attachments && msg.attachments.length > 0 && (
                    <div className="flex gap-2 flex-wrap mb-2 justify-end">
                        {msg.attachments.map((att, idx) => (
                            att.mimeType.startsWith('image') && (
                                <img 
                                    key={idx}
                                    src={`data:${att.mimeType};base64,${att.data}`}
                                    alt="Uploaded content"
                                    className="max-w-[200px] rounded-xl border border-[#333]"
                                />
                            )
                        ))}
                    </div>
                )}

                {msg.image ? (
                    <div className="bg-[#18181b] p-3 border border-[#27272a] rounded-2xl rounded-tl-none flex flex-col gap-2 shadow-lg overflow-hidden">
                        <img 
                            src={`data:image/png;base64,${msg.image.base64}`}
                            alt={msg.image.prompt}
                            className="rounded-xl max-w-full"
                        />
                        <div className="flex justify-between items-center px-2 py-1">
                            <span className="text-xs text-gray-500">Generated by {msg.image.model}</span>
                            <button 
                                onClick={() => navigator.clipboard.writeText(msg.image!.prompt)}
                                className="text-gray-400 hover:text-white transition-colors" 
                                title="Copy Prompt"
                            >
                                <Copy className="w-3 h-3" />
                            </button>
                        </div>
                    </div>
                ) : (
                    <div 
                    className={`relative px-5 py-3.5 text-[15px] leading-relaxed shadow-md transition-all ${
                        msg.role === Role.USER 
                        ? 'bg-blue-600 text-white rounded-2xl rounded-tr-sm' 
                        : 'bg-[#27272a] text-gray-100 rounded-2xl rounded-tl-sm border border-[#333]'
                    }`}
                    >
                    {msg.role === Role.USER ? (
                        <p className="whitespace-pre-wrap break-words">{msg.content}</p>
                    ) : (
                        <div className="markdown-content">
                            <ReactMarkdown
                            components={{
                                code({node, inline, className, children, ...props}: any) {
                                const match = /language-(\w+)/.exec(className || '')
                                return !inline && match ? (
                                    <div className="rounded-lg overflow-hidden my-3 border border-[#333] shadow-sm">
                                        <div className="bg-[#1e1e1e] px-3 py-1.5 text-xs text-gray-400 font-mono border-b border-[#333] flex justify-between items-center">
                                            <span>{match[1]}</span>
                                            <button onClick={() => navigator.clipboard.writeText(String(children))} className="text-[10px] hover:text-white">Copy</button>
                                        </div>
                                        <SyntaxHighlighter
                                        {...props}
                                        style={vscDarkPlus}
                                        language={match[1]}
                                        PreTag="div"
                                        customStyle={{ margin: 0, padding: '1rem', background: '#0d0d0d', fontSize: '0.85rem' }}
                                        >
                                        {String(children).replace(/\n$/, '')}
                                        </SyntaxHighlighter>
                                    </div>
                                ) : (
                                    <code {...props} className={`${className} bg-black/30 px-1.5 py-0.5 rounded text-blue-100 font-mono text-sm`}>
                                    {children}
                                    </code>
                                )
                                },
                                p({ children }) {
                                    return <p className="mb-3 last:mb-0">{children}</p>
                                },
                                ul({ children }) {
                                    return <ul className="list-disc pl-5 mb-3 space-y-1">{children}</ul>
                                },
                                ol({ children }) {
                                    return <ol className="list-decimal pl-5 mb-3 space-y-1">{children}</ol>
                                },
                                li({ children }) {
                                    return <li className="pl-1">{children}</li>
                                },
                                a({ href, children }) {
                                    return <a href={href} target="_blank" rel="noreferrer" className="text-blue-400 hover:underline break-all">{children}</a>
                                },
                                blockquote({ children }) {
                                    return <blockquote className="border-l-2 border-gray-500 pl-4 italic my-2 text-gray-400">{children}</blockquote>
                                }
                            }}
                            >
                            {msg.content}
                            </ReactMarkdown>
                        </div>
                    )}
                    </div>
                )}

                {/* Grounding Sources */}
                {msg.groundingMetadata?.webSources && msg.groundingMetadata.webSources.length > 0 && (
                    <div className="mt-2 flex flex-wrap gap-2 ml-1">
                        <div className="w-full flex items-center gap-2 text-xs text-gray-500 mb-1 uppercase tracking-wider font-semibold">
                            <Search className="w-3 h-3" />
                            Sources
                        </div>
                        {msg.groundingMetadata.webSources.map((source, idx) => (
                            <a 
                                key={idx} 
                                href={source.uri} 
                                target="_blank" 
                                rel="noopener noreferrer"
                                className="flex items-center gap-2 px-3 py-2 bg-[#1a1a1a] border border-[#333] rounded-lg text-xs text-gray-400 hover:text-blue-400 hover:border-blue-500/30 hover:bg-[#222] transition-all max-w-[240px] truncate group"
                            >
                                <Globe className="w-3 h-3 flex-shrink-0 group-hover:text-blue-400" />
                                <span className="truncate">{source.title}</span>
                            </a>
                        ))}
                    </div>
                )}
            </div>

            {msg.role === Role.USER && (
                <div className="w-8 h-8 rounded-full bg-surfaceHighlight flex-shrink-0 flex items-center justify-center mt-1 border border-border">
                    <User className="w-4 h-4 text-gray-400" />
                </div>
            )}
            </div>
        )
      })}
      {isLoading && !messages.some(m => m.isStreaming || m.isGeneratingImage) && (
        // Fallback loader if no message is currently streaming/generating but we are loading
        <div className="flex gap-4 max-w-4xl mx-auto animate-pulse">
           <div className="w-8 h-8 rounded-full bg-gradient-to-br from-blue-500 to-purple-600 flex-shrink-0 flex items-center justify-center shadow-lg mt-1 border border-white/10">
                <NexusLogo className="w-5 h-5" />
           </div>
           <div className="flex items-center gap-2 h-10 bg-[#27272a] px-4 rounded-2xl rounded-tl-none border border-[#333]">
                <div className="w-1.5 h-1.5 bg-gray-500 rounded-full animate-bounce [animation-delay:-0.3s]"></div>
                <div className="w-1.5 h-1.5 bg-gray-500 rounded-full animate-bounce [animation-delay:-0.15s]"></div>
                <div className="w-1.5 h-1.5 bg-gray-500 rounded-full animate-bounce"></div>
           </div>
        </div>
      )}
      <div ref={bottomRef} />
    </div>
  );
};
